### ISSUE TITLE
Align Sonar Argo Application with its Helm Chart Dependency

### ISSUE THREAD

**Issue by Artem-Zahumonnyi** [epam/edp-cluster-add-ons#42]
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonar
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  source:
    repoURL: {{ .Values.repoUrl }}
    path: add-ons/sonar
    targetRevision: {{ .Values.targetRevision }}
    helm:
      values: |
        sonar:   # <---- Change it to sonarqube
```
