### ISSUE TITLE
Align values file of the sonar-operator

### ISSUE THREAD

**Issue by Artem-Zahumonnyi** [epam/edp-cluster-add-ons#43]
We can not set these parameters without defining the child chart name:
https://github.com/epam/edp-cluster-add-ons/blob/main/add-ons/sonar-operator/values.yaml#L1-L35

For example,
```yaml
sonar-operator: # <--- This part is missing.
  # -- component name
  name: sonar-operator
  annotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  image:
    # -- EDP sonar-operator Docker image name. The released image can be found on [Dockerhub](https://hub.docker.com/r/epamedp/sonar-operator)
    repository: epamedp/sonar-operator
    # if not defined then .Chart.AppVersion is used
    # -- EDP sonar-operator Docker image tag. The released image can be found on [Dockerhub](https://hub.docker.com/r/epamedp/sonar-operator/tags)
    tag: 3.1.0
  imagePullPolicy: "IfNotPresent"
  
  resources:
    limits:
      memory: 192Mi
    requests:
      cpu: 50m
      memory: 64Mi
  
  # -- Additional volumes to be added to the pod
  extraVolumes: []
  #  - name: custom-ca
  #    secret:
  #      defaultMode: 420
  #      secretName: custom-ca
  
  # -- Additional volumeMounts to be added to the container
  extraVolumeMounts: []
  #  - name: custom-ca
  #    mountPath: /etc/ssl/certs/CA.crt
  #    readOnly: true
  #    subPath: CA.crt
```
