### ISSUE TITLE
Add MutatingWebhookConfiguration and ValidatingWebhookConfiguration into ignoreDifferences (Capsule)

### ISSUE THREAD

**Issue by Artem-Zahumonnyi** [epam/edp-cluster-add-ons#44]
```yaml
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
      - .webhooks[].clientConfig.caBundle
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
      - .webhooks[].clientConfig.caBundle
```
![image](https://github.com/epam/edp-cluster-add-ons/assets/51204821/16a502e5-aaa5-46f3-af12-cbd0296c0840)
