### ISSUE TITLE
Align values of the Nexus Argo CD Application

### ISSUE THREAD

**Issue by Artem-Zahumonnyi** [epam/edp-cluster-add-ons#45]
https://github.com/epam/edp-cluster-add-ons/blob/main/chart/templates/nexus.yaml#L18

**Comment by Artem-Zahumonnyi** [comment]
Set 
```yaml
    helm:
      values: |
        nexus-repository-manager:
        {{- toYaml .Values.nexus | nindent 10 }}
```
