### ISSUE TITLE
Fix Application name of the Nexus-operator

### ISSUE THREAD

**Issue by Artem-Zahumonnyi** [epam/edp-cluster-add-ons#51]
We are changing the application configuration as follows:

From the current state:
```yaml
kind: Application
metadata:
  name: {{ .Values.destinationServer}}-nexus-operator
  namespace: {{ .Values.argoNamespace | default "argocd" }}
```

To the new state:

```yaml
kind: Application
metadata:
  name: nexus-operator
  namespace: {{ .Values.argoNamespace | default "argocd" }}
```
