### ISSUE TITLE
Option to Exclude oauth2-proxy Deployment in Nexus Addon

### ISSUE THREAD

**Issue by Artem-Zahumonnyi** [epam/edp-cluster-add-ons#52]
We are changing the application configuration as follows:

From the current state:
```yaml
- name: oauth2-proxy
  version: 6.16.1
  repository: https://oauth2-proxy.github.io/manifests/
```

To the new state:

```yaml
- name: oauth2-proxy
  version: 6.16.1
  repository: https://oauth2-proxy.github.io/manifests/
  condition: oauth2-proxy.enabled
```
