### ISSUE TITLE
Extensions-OIDC and Sonar-operator addons contain the same Keycloak roles for Sonar

### ISSUE THREAD

**Issue by Artem-Zahumonnyi** [epam/edp-cluster-add-ons#64]
The `extensions-oidc` addon contains the following `KeycloakRealmRoleBatch`:

```yaml
apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealmRoleBatch
metadata:
  name: "default-roles"
spec:
  realmRef:
    kind: ClusterKeycloakRealm
    name: main
  roles:
    - name: developer
      composite: true
      description: "default developer role"
      isDefault: false
      composites:
        - name: sonar-developers
    - name: administrator
      composite: true
      description: "default administrator role"
      composites:
        - name: sonar-administrators
```

The `sonar-operator` addon contains the following `KeycloakRealmRoleBatch` resources:

```yaml
{{- if .Values.oidc.enabled }}
apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealmRoleBatch
metadata:
  name: "sonar-administrators"
spec:
  realmRef:
    kind: ClusterKeycloakRealm
    name: main
  roles:
    - name: sonar-administrators
      description: "default developer role"
{{ end }}
```

```yaml
{{- if .Values.oidc.enabled }}
apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealmRoleBatch
metadata:
  name: "sonar-developers"
spec:
  realmRef:
    kind: ClusterKeycloakRealm
    name: main
  roles:
    - name: sonar-developers
      description: "default developer role"
{{ end }}

```
