### ISSUE TITLE
Update ArgoCD component to the latest stable version

### ISSUE THREAD

**Issue by SergK** [epam/edp-cluster-add-ons#70]
**Is your feature request related to a problem? Please describe.**
Currently, our ArgoCD installation approach utilizes `envFrom` for Argo ApplicationSet controller configuration. This method may not be the most efficient or clear way to manage the configuration settings.

**Describe the solution you'd like**
I propose we update the ArgoCD installation approach to explicitly define configuration settings within the `values.yaml` file. Specifically, we should use the following settings:

```yaml
  params:
    applicationsetcontroller.namespaces: "edp"
    applicationsetcontroller.enable.scm.providers: "false"
    server.insecure: true
    application.namespaces: "edp"
```

This change aims to make the configuration process more straightforward and manageable.

**Describe alternatives you've considered**
An alternative could involve continuing to use `extraEnv` but enhancing documentation to make the process clearer. However, explicitly defining the settings as proposed would likely be more user-friendly and reduce potential for confusion.

**Additional context**
Transitioning to a more explicit configuration approach can improve clarity and ease of use for our ArgoCD installation process, benefiting users with a smoother setup experience.

`labels`: 'CodeMie'

https://github.com/epam/edp-cluster-add-ons/blob/main/add-ons/argo-cd/values.yaml#L33
